version: "2"
services:
  redis:
    image: convox/redis
    ports:
      - 6379
  web:
    build: .
    labels:
      - convox.cron.helloworld=0 * * * ? bin/helloworld
      - convox.port.443.protocol=tls
      - convox.port.443.proxy=true
    ports:
      - 80:4000
      - 443:4001
  worker:
    build: .
    command: bundle exec sidekiq
    links:
      - redis
